import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import "tailwindcss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <header className="w-full text-left bg-gray-100 p-4">
            <h1 >The Akmal Website</h1>
          </header>
          
        <div className="page-container">
        

          <main>{children}</main>

         </div>

        

          <footer className="w-full text-left bg-gray-100 p-4">
            <p>© 2025 My Website</p>
            <nav className="nav-links">
            <Link href = "/contact">☎️ Kontak Aku</Link> |{" "}
            <Link href = "/about">👤 Tentang</Link> |{" "}
            <Link href = "/">🏠 Beranda</Link> 
            </nav>
          </footer>

        
      </body>
    </html>
  );
}
          
         
          
