import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

    
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex ${geistSans.variable} ${geistMono.variable}`}>
        <main className="flex-1 p-6 bg-black min-h-screen">
          {children}
        </main>
      </body>
    </html>
    
  );
}
